---
title: "DataWrangling"
author: "Kathleen Mason"
date: "4/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Getting Set Up}
getwd()
library(dplyr)
library(tidyr)
library(tidyverse)
library(lubridate)

USGS_ElwhaDischarge_1<-read.csv("./Raw/USGS_ElwhaDischarge_raw.csv")
```

```{r Wrangling}

#Select only important columns
USGS_ElwhaDischarge_2<-USGS_ElwhaDischarge_1 %>% select(Day:Daily.SSC..mg.L., Daily.Suspended.Sediment.Load..tonnes.:Daily.SS.Load.of.sand..tonnes., Project.year)

#Date and ordering by date
USGS_ElwhaDischarge_2$Day <- as.Date(USGS_ElwhaDischarge_2$Day, format = "%m/%d/%Y")
USGS_ElwhaDischarge_2<-USGS_ElwhaDischarge_2[order(as.Date(USGS_ElwhaDischarge_2$Day, format="%Y-%m-%d")),]


```

```{r Changing Column Names}

colnames(USGS_ElwhaDischarge_2)<- c("Date","DailyDischarge","DailySSC", "DailySuspendedSediment", "DailySSfines", "DailySSsand", "ProjectYear")



```

```{r Saving new file for analysis}

write.csv(USGS_ElwhaDischarge_2, row.names = FALSE, file = ("./Processed/USGS_ElwhaRiver_processed.csv"))

```

```{r Water Discharge Data}
#USGS_ElwhaWaterDischarge<-read.csv("./Raw/USGS_ElwhaWaterDischarge_raw.csv")

#USGS_ElwhaWaterDischarge = USGS_ElwhaWaterDischarge[-1,]
#USGS_ElwhaWaterDischarge<- select(USGS_ElwhaWaterDischarge, year_nu:mean_va)

#class(USGS_ElwhaWaterDischarge$year_nu)
#class(USGS_ElwhaWaterDischarge$month_nu)


#USGS_ElwhaWaterDischarge$year_nu<-as.character(USGS_ElwhaWaterDischarge$year_nu)
#USGS_ElwhaWaterDischarge$month_nu<-as.character(USGS_ElwhaWaterDischarge$month_nu)




#USGS_ElwhaWaterDischarge<-USGS_ElwhaWaterDischarge[
  #with(USGS_ElwhaWaterDischarge, order(year_nu, month_nu)),]



```

