---
title: "DataExploration_ElwhaRiver"
author: "Kathleen Mason"
date: "4/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Getting setup}

getwd()
setwd("/Users/kathleenmason/Documents/DUKE/Data Analytics/ElwhaRiver/DataProject_ElwhaRiver")
USGS_ElwhaRiverDischarge<-read.csv("./Processed/USGS_ElwhaRiver_processed.csv")
```

```{r exploring to begin}

dim(USGS_ElwhaRiverDischarge)
#1843 points, 7 columns
str(USGS_ElwhaRiverDischarge)

class(USGS_ElwhaRiverDischarge$ProjectYear)
head(USGS_ElwhaRiverDischarge$Date)
tail(USGS_ElwhaRiverDischarge$Date)
#Dates go from 2011-09-15 to 2016-09-30

summary(USGS_ElwhaRiverDischarge$DailyDischarge)
summary(USGS_ElwhaRiverDischarge$DailySSC)
summary(USGS_ElwhaRiverDischarge$DailySuspendedSediment)
summary(USGS_ElwhaRiverDischarge$DailySSfines)
summary(USGS_ElwhaRiverDischarge$DailySSsand)

str(USGS_ElwhaRiverDischarge$ProjectYear) #5 project years

mean(USGS_ElwhaRiverDischarge$DailyDischarge)

#plots
ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailyDischarge, color = ProjectYear))
  
ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailySSfines, color=ProjectYear))

ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailySSsand, color=ProjectYear))
```

Notes for visualizations:

*Need dates to be listed by year
*Insert line when project began and when it ended
*Project year column isn;t very helpful


Research Question:
How did Dam removal effect sediment flow in the Elwha River?
>Look at Dailydischarge over time
>any significant differences between sand and fine grained particles in suspension

```{r Exploration Graphs to Include}

mytheme <- theme_light(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

#1 Daily Discharge/time
ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailyDischarge), size=1.25, color="skyblue4")+
  ylab(expression(Daily~Discharge~(m^2/s)))+
  mytheme
  

#2 DAily SSfine/time
ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailySSfines), size=1, color="slateblue")+
  ylab("Daily Suspended Fine-Grained Sediment (tonnes)")+
  mytheme

#3 Daily SSsand/time
ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailySSsand), size=1, color="gray20")+
  ylab("Daily Suspended Sand Sediment (tonnes)")+
  mytheme


#4 SSsand and SSfine
ggplot(USGS_ElwhaRiverDischarge) +
  geom_point(aes(x = Date, y = DailySSfines), size=1, color="royalblue", alpha=0.25)+
  geom_point(aes(x = Date, y = DailySSsand), size=1, color="gray20", alpha=0.25)+
  ylab("Daily Suspended Sediment(tonnes)")+
  mytheme

#4 Total sediment discharge/time
ggplot(USGS_ElwhaRiverDischarge) +
  geom_line(aes(x = Date, y = TotalSedimentDischarge), size=.5, color="royalblue")+
  ylab("Total Sediment Discharge (tonnes)")+
  mytheme


#5 daily discharge (water)/total sediment discharge

ggplot(USGS_ElwhaRiverDischarge, aes(DailyDischarge, TotalSedimentDischarge)) +
  geom_smooth(method='lm', formula=y~x, color="gray20")+
  geom_point(color="slateblue", size=1, alpha=0.5)+
  ylab("Total Sediment Discharge (tonnes)")+
  xlab(expression(Daily~Discharge~(m^2/s)))+
  ylim(0,NA)+
  xlim(0, NA)+
  mytheme


```

